name: Connect-and-Test
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared

      - name: Start Bridge Tunnel
        run: |
          # برقراری پل ارتباطی
          sudo ./cloudflared access tcp --hostname alpine-refer-upgrade-fold.trycloudflare.com --url localhost:443 &
          
          # ۳ ثانیه صبر برای پایداری تونل
          sleep 3

      - name: Check Connection (LOG)
        run: |
          echo "Checking connection to your VPS through the tunnel..."
          # ارسال یک دستور ساده به پورت 443 محلی (که به سرور شما پل شده)
          if nc -zv localhost 443; then
            echo "SUCCESS: GitHub is connected to your VPS!"
          else
            echo "FAILED: GitHub cannot reach your VPS. Check your Server or Cloudflare Tunnel."
          fi
          
          # زنده نگه داشتن برای مشاهده نتایج
          sleep 21600
